name: srbs
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.0.1+2

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  curved_labeled_navigation_bar: ^2.0.2
  material_design_icons_flutter: ^7.0.7296
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  shared_preferences: ^2.2.0
  flutter_easyloading: ^3.0.5
  skeletons: ^0.0.3
  intl: ^0.19.0
  dropdown_button2: ^2.3.9
  ns_upi: ^1.0.2
  path_provider: ^2.1.2
  open_filex: ^4.4.0
  alt_sms_autofill: ^1.0.0
  skeletonizer: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/logo/
    - assets/icons/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Averia Serif Libre
      fonts:
        - asset: assets/fonts/AveriaSerifLibre-Bold.ttf
        - asset: assets/fonts/AveriaSerifLibre-Italic.ttf
          style: italic
        - asset: assets/fonts/AveriaSerifLibre-Light.ttf
        - asset: assets/fonts/AveriaSerifLibre-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
